---
title: "Error sources in vegetation modeling"
subtitle: "UMass MassMarsh UAS project"
author: "Brad Compton"
date: "`r timestamp <- lubridate::stamp('February 4, 2025', quiet = TRUE); timestamp(lubridate::now(tz = 'America/New_York'))`"
output: html_document
---
<style>
/* Limit body text width, center paragraphs and lists */
.main-container p,
.main-container ul,
.main-container ol,
.main-container blockquote {
max-width: 850px;
margin-left: auto;
margin-right: auto;
}

/* Do NOT constrain code output or code blocks */
.main-container pre,
.main-container pre.r,
.main-container code,
.main-container .r-output {
max-width: none !important;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA)
options(width = 150)

library(marshmap)
```


| CCR | model | error source  | resolvability | approach | who |
| ---- | --------------------------------- | -------------------------------------------------------------------------------------------------------- | --------------------------------- | ------------------------------------------------------------- | ----------- |
| 100% | perfect fit |  | |  |  |
| | | **inherent error** | not resolvable | none  | --- |
| | | **pixel-based** modeling approach poorly matched to heterogeneous data with high spatial autocorrelation | likely? | U-Net | Brad |
| | | no **LiDAR**  | 100% | process LiDAR | Ethan  |
| | | poor **variable selection**  | high | try fewer high-quality orthos + variable selection | Brad |
| | | **insufficient orthos** (missing seasons, poor quality, areas of missing data) | minimal | repair as possible | Ryan & crew |
| | | **missing years** of orthos  | moderate | process 2023 (and 2024?) | Ryan & crew |
| | | inadequate sample of **PI data**  | 100% | need many scattered PI polys per year  | Angel **done** |
| | | **mowing** and other management interventions | high | use PI to map areas with mowing for deletion | Ryan |
| | | **field poly errors** and boundary slop  | modest  | careful review of field data  | Ryan |
| | | **temporaral mismatch** between field data and orthos | high, but will reduce sample size | need dates for field polys, then select years matching orthos | Ryan's crew |
| | | inadequate **field sample size** (with severe spatial autocorrelation) | not resolvable with past data |  | --- |
| 40% | random forest w/rich upscaling |  | |  |  |


# Lessons for future field years
1. Match field work and flights in a single year
2. Scatter field polys more broadly across site with larger sample sizes, both in polys and pixels
3. Make sure flights entire site, including all field polys
4. Fly all seasons
5. Don't fly when it's partly cloudy
6. Better coordination with marsh managers so we don't get our sites mowed under us again